[package]
name = "bevy_tiles_ecs"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
license-file.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]

[lints]
workspace = true
