name: Release

on:
  push:
    tags:
      - '*'

env:
  add_binaries_to_github_release: true
  use_git_lfs: true


jobs:

  # Build for Linux
  release-linux:
    runs-on: ubuntu-latest
    environment: publish

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: ${{ env.use_git_lfs }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
      - name: install dependencies
        run: |
          sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Test
        run: |
          cargo test --release --target x86_64-unknown-linux-gnu

      - name: Get Dependency
        run: |
          cargo install cargo-release

      - name: Login
        run: |
          cargo login ${{ secrets.CARGO_TOKEN }}

      - name: Publish
        run: |
          cargo release publish \
            --workspace \
            --execute \
            --all-features \
